default: &default
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: db/test_rubygems.sqlite3

test_rubygems:
  <<: *default
  database: db/test_rubygems.sqlite3

test_npm:
  <<: *default
  database: db/test_npm.sqlite3

test_pypi:
  <<: *default
  database: db/test_pypi.sqlite3

test_packagist:
  <<: *default
  database: db/test_packagist.sqlite3

production:
  <<: *default
  # default to the rubygems db for the production environment
  database: db/production_rubygems.sqlite3

production_rubygems:
  <<: *default
  database: db/production_rubygems.sqlite3

production_npm:
  <<: *default
  database: db/production_npm.sqlite3

production_pypi:
  <<: *default
  database: db/production_pypi.sqlite3

production_packagist:
  <<: *default
  database: db/production_packagist.sqlite3

# git.legal core databases
git_legal_development:
  adapter: postgresql
  database: git_legal_development

git_legal_production:
  adapter: postgresql
  encoding: unicode
  database: production
  username: gitlegal
  password: <%= ENV['GIT_LEGAL_DB_PASS'] %>
  host: production.cutu6pliwl23.us-west-2.rds.amazonaws.com
  port: 5432
