default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: git_legal-codeclimate_development

git_legal_development:
  <<: *default
  database: git_legal_development

test:
  <<: *default
  database: git_legal-codeclimate_test

production:
  <<: *default
  database: git_legal-codeclimate_production
  username: git_legal-codeclimate
  password: <%= ENV['GIT_LEGAL-CODECLIMATE_DATABASE_PASSWORD'] %>
