default: &default
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3

# git.legal core databases
git_legal_development:
  adapter: postgresql
  database: git_legal_development
