# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae831d771b2b1faa12d800d38ab02102c17d5125bcfca4d46e42f7886e8ca4aced5c8ce637f6799edd5b0a748a60ab94dddee651d5c1cd82ae31c2ed9002ab77

test:
  secret_key_base: e23f2c1958c05aad9a2990256d9299cf16f58d6b99424b0ddf7d9cb5fe422676f426a37dada32167aab632a2ae137cd759610aa27a9ee7806a2f6c32fd224cd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
